-- Add missing columns to sigma_rules
ALTER TABLE sigma_rules 
  ADD COLUMN IF NOT EXISTS level TEXT DEFAULT 'medium',
  ADD COLUMN IF NOT EXISTS status TEXT DEFAULT 'experimental',
  ADD COLUMN IF NOT EXISTS tags TEXT[] DEFAULT '{}',
  ADD COLUMN IF NOT EXISTS author TEXT DEFAULT 'Security Analyst',
  ADD COLUMN IF NOT EXISTS references TEXT[] DEFAULT '{}',
  ADD COLUMN IF NOT EXISTS logsource JSONB,
  ADD COLUMN IF NOT EXISTS detection JSONB,
  ADD COLUMN IF NOT EXISTS condition TEXT,
  ADD COLUMN IF NOT EXISTS fields TEXT[] DEFAULT '{}',
  ADD COLUMN IF NOT EXISTS falsepositives TEXT[] DEFAULT '{}',
  ADD COLUMN IF NOT EXISTS updatedAt TIMESTAMP(3);

-- Add missing columns to yara_rules
ALTER TABLE yara_rules 
  ADD COLUMN IF NOT EXISTS level TEXT DEFAULT 'high',
  ADD COLUMN IF NOT EXISTS tags TEXT[] DEFAULT '{}',
  ADD COLUMN IF NOT EXISTS author TEXT DEFAULT 'Security Analyst',
  ADD COLUMN IF NOT EXISTS strings JSONB,
  ADD COLUMN IF NOT EXISTS condition TEXT,
  ADD COLUMN IF NOT EXISTS imports TEXT[] DEFAULT '{}',
  ADD COLUMN IF NOT EXISTS version TEXT DEFAULT '1.0',
  ADD COLUMN IF NOT EXISTS reference TEXT,
  ADD COLUMN IF NOT EXISTS hash TEXT,
  ADD COLUMN IF NOT EXISTS updatedAt TIMESTAMP(3);

-- Add missing columns to use_cases
ALTER TABLE use_cases 
  ADD COLUMN IF NOT EXISTS mitreTactic TEXT,
  ADD COLUMN IF NOT EXISTS mitreTechnique TEXT,
  ADD COLUMN IF NOT EXISTS platform TEXT DEFAULT 'windows',
  ADD COLUMN IF NOT EXISTS logsource TEXT,
  ADD COLUMN IF NOT EXISTS detectionLogic JSONB,
  ADD COLUMN IF NOT EXISTS falsepositives TEXT[] DEFAULT '{}',
  ADD COLUMN IF NOT EXISTS status TEXT DEFAULT 'draft',
  ADD COLUMN IF NOT EXISTS priority TEXT DEFAULT 'medium',
  ADD COLUMN IF NOT EXISTS tags TEXT[] DEFAULT '{}',
  ADD COLUMN IF NOT EXISTS author TEXT DEFAULT 'Security Analyst',
  ADD COLUMN IF NOT EXISTS tests JSONB,
  ADD COLUMN IF NOT EXISTS updatedAt TIMESTAMP(3);
